# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0654aca1f7bb554ce8c13c7185cf0f2e"
name = "click-&-collect-flirt-adult"
handle = "click-collect-flirt-adult"
application_url = "https://click-n-collect-flirt-adult-f70cdb5d038f.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "saasintegration.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://click-n-collect-flirt-adult-f70cdb5d038f.herokuapp.com/auth/callback",
  "https://click-n-collect-flirt-adult-f70cdb5d038f.herokuapp.com/auth/shopify/callback",
  "https://click-n-collect-flirt-adult-f70cdb5d038f.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://click-n-collect-flirt-adult-f70cdb5d038f.herokuapp.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://click-n-collect-flirt-adult-f70cdb5d038f.herokuapp.com/webhooks/app/uninstalled"

[pos]
embedded = false
