# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "318ace28f9da788f38afadd8339bb795"
name = "worklocker"
handle = "worklocker-1"
application_url = "https://exercises-figure-scottish-visitor.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "saas-click-collect.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_locales,read_locations,read_product_listings,read_products,read_publications,read_script_tags,write_content,write_inventory,write_locations,write_products,write_publications,write_script_tags,write_shipping"

[auth]
redirect_urls = [
  "https://exercises-figure-scottish-visitor.trycloudflare.com/auth/callback",
  "https://exercises-figure-scottish-visitor.trycloudflare.com/auth/shopify/callback",
  "https://exercises-figure-scottish-visitor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
